// This file is autogenerated

#pragma once

#include "chPrerequisitesUtilities.h"
#include "PingCommand.h"
#include "ReactCommand.h"

typedef std::function<std::shared_ptr<chBot::BaseCommand>()> CommandCreator;
enum class CommandType {
  PING,
  REACT,
};

std::unordered_map<CommandType, CommandCreator> LOADED_COMMANDS = {
  {CommandType::PING, [](){ return std::make_shared<chBot::PingCommand>(); } },
  {CommandType::REACT, [](){ return std::make_shared<chBot::ReactCommand>(); } },
};

std::unordered_map<std::string, CommandType> COMMAND_NAME_TO_TYPE = {
  {"ping", CommandType::PING},
  {"react", CommandType::REACT},
};
